"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import environ
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Process environment takes precedence over the optional, ignored local file.
env = environ.Env()
env.read_env(BASE_DIR / '.env', overwrite=False)
SECRET_KEY = env('DJANGO_SECRET_KEY')
if not SECRET_KEY.strip() or SECRET_KEY == 'replace-with-a-generated-local-secret':
    raise ImproperlyConfigured('Set DJANGO_SECRET_KEY to a generated secret in the environment or backend/.env.')
DEBUG = env.bool('DJANGO_DEBUG', default=False)
ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=[])
FRONTEND_URL = env('FRONTEND_URL', default='').rstrip('/')
CORS_ALLOWED_ORIGINS = [FRONTEND_URL] if FRONTEND_URL else []
if DEBUG:
    CORS_ALLOWED_ORIGINS = list(dict.fromkeys([
        *CORS_ALLOWED_ORIGINS,
        'http://localhost:5173',
        'http://127.0.0.1:5173',
    ]))
CORS_ALLOW_ALL_ORIGINS = False
CORS_URLS_REGEX = r'^/api/.*$'
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = list(CORS_ALLOWED_ORIGINS)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ['rest_framework.authentication.SessionAuthentication'],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'],
    'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer'],
}


# Application definition

AUTH_USER_MODEL = 'users.User'

INSTALLED_APPS = [
    'rest_framework',
    'corsheaders',
    'users.apps.UsersConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

try:
    database_url = env('DATABASE_URL')
    if not database_url.startswith(('postgres://', 'postgresql://', 'psql://')):
        raise ImproperlyConfigured('DATABASE_URL must use a PostgreSQL URL scheme.')
    DATABASES = {'default': env.db_url_config(database_url)}
except (ImproperlyConfigured, ValueError):
    raise ImproperlyConfigured('Set DATABASE_URL to a valid PostgreSQL connection URL.') from None
if DATABASES['default'].get('ENGINE') != 'django.db.backends.postgresql':
    raise ImproperlyConfigured('DATABASE_URL must configure PostgreSQL; SQLite fallback is not supported.')
if not DATABASES['default'].get('NAME'):
    raise ImproperlyConfigured('DATABASE_URL must include a PostgreSQL database name.')



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
