# Generated by Django 5.2.17 on 2026-10-07 17:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft')], default='draft', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('asset', 'Asset'), ('income', 'Income'), ('expense', 'Expense'), ('equity', 'Equity')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='finance.journalentry')),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='finance.ledgeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('bank', 'Bank'), ('wallet', 'Wallet'), ('cash', 'Cash'), ('other', 'Other')], max_length=10)),
                ('institution_name', models.CharField(blank=True, max_length=120)),
                ('subtype', models.CharField(blank=True, max_length=80)),
                ('last_four', models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator('\\A[0-9]{4}\\Z', 'Enter exactly four digits.')])),
                ('is_active', models.BooleanField(default=True, help_text='False means archived; historical references remain valid.')),
                ('include_in_total', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('ledger_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_account', to='finance.ledgeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='False means archived; historical references remain valid.')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='finance.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('ledger_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='finance.ledgeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=24)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('idempotency_key', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft')], default='draft', max_length=10)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.financialaccount')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.category')),
                ('destination_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='finance.financialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='journalentry',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entry', to='finance.transaction'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['asset', 'income', 'expense', 'equity'])), name='finance_ledger_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit__gt', 0), ('debit__isnull', False), ('debit__lt', Decimal('1000000000000000000')), ('credit__isnull', True)), models.Q(('credit__gt', 0), ('credit__isnull', False), ('credit__lt', Decimal('1000000000000000000')), ('debit__isnull', True)), _connector='OR'), name='finance_line_positive_debit_xor_credit'),
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['bank', 'wallet', 'cash', 'other'])), name='finance_account_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.CheckConstraint(condition=models.Q(('last_four', ''), ('last_four__regex', '\\A[0-9]{4}\\Z'), _connector='OR'), name='finance_account_last_four_valid'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['income', 'expense'])), name='finance_category_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('parent__isnull', True), models.Q(('parent', models.F('pk')), _negated=True), _connector='OR'), name='finance_category_not_self_parent'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('user', 'idempotency_key'), name='finance_transaction_user_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['income', 'expense', 'transfer'])), name='finance_transaction_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('amount__isnull', False), ('amount__lt', Decimal('1000000000000000000'))), name='finance_transaction_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft')), name='finance_transaction_draft_only'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'transfer'), _negated=True), ('category__isnull', True), _connector='OR'), name='finance_transfer_no_category'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'transfer'), ('destination_account__isnull', True), _connector='OR'), name='finance_destination_transfer_only'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('account__isnull', True), ('destination_account__isnull', True), models.Q(('account', models.F('destination_account')), _negated=True), _connector='OR'), name='finance_transfer_distinct_accounts'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft')), name='finance_journal_draft_only'),
        ),
    ]
