# Generated by Django 5.2.17 on 2026-10-08 04:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='finance_transaction_kind_valid',
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='finance_transfer_no_category',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer'), ('opening_balance', 'Opening balance'), ('adjustment', 'Balance adjustment')], max_length=15),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['income', 'expense', 'transfer', 'opening_balance', 'adjustment'])), name='finance_transaction_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['income', 'expense']), ('category__isnull', True), _connector='OR'), name='finance_category_classified_only'),
        ),
    ]
