# Generated by Django 5.2.17 on 2026-10-02 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='base_currency',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('\\A[A-Z]{3}\\Z', 'Use a three-letter uppercase currency code.')]),
        ),
    ]
